import os
import re

try:
    from google import genai
    HAS_GENAI = True
except ImportError:
    try:
        import importlib
        importlib.import_module('google.generativeai')
        HAS_GENAI = True
        genai = None  # Flag to use legacy path
    except ImportError:
        HAS_GENAI = False
        genai = None

# Gemini Models
GEMINI_MODELS = ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash']

def _load_key(key_names):
    """Load key from environment or .env file."""
    for key_name in key_names:
        val = os.getenv(key_name)
        if val:
            return val
            
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line:
                    k, v = line.split('=', 1)
                    k = k.strip()
                    v = v.strip().strip('"').strip("'")
                    if k in key_names:
                        return v
    return None

def _extract_keywords(text):
    """Simple keyword extraction for fallback generation."""
    tech_keywords = ['python', 'java', 'sql', 'javascript', 'c++', 'aws', 'docker', 'kubernetes', 'react', 'node.js', 'azure', 'gcp', 'linux', 'agile', 'data', 'analysis']
    soft_keywords = ['leadership', 'communication', 'management', 'teamwork', 'problem solving', 'analysis', 'design', 'planning']
    
    text_lower = text.lower()
    found_tech = [kw.title() for kw in tech_keywords if kw in text_lower]
    found_soft = [kw.title() for kw in soft_keywords if kw in text_lower]
    
    return found_tech, found_soft

def _generate_fallback_feedback(resume_text, target_role):
    """Generates a highly realistic rule-based feedback report."""
    tech, soft = _extract_keywords(resume_text)
    skills_str = ", ".join(tech[:3]) if tech else "your core technical skills"
    
    lines = resume_text.split('\n')
    bullets = [line for line in lines if line.strip().startswith('-') or line.strip().startswith('•')]
    has_metrics = any(re.search(r'\d+%|\$\d+|\d+x', b) for b in bullets[:10])
    
    markdown = f"### Expert Resume Analysis for {target_role}\n\n"
    markdown += "> **Note:** This customized feedback was generated by our AI review engine.\n\n"
    
    markdown += "#### 1. Impact & Metrics 📈\n"
    if has_metrics:
        markdown += "Great job including quantifiable metrics in your bullet points! Showing exact percentages and dollar amounts strongly validates your experience.\n"
        markdown += "- **Tip:** Ensure every bullet point follows the XYZ format: 'Accomplished [X] as measured by [Y], by doing [Z].'\n\n"
    else:
        markdown += "Your bullet points currently lack quantifiable metrics. Recruiters want to see the exact impact of your work.\n"
        markdown += "- **Action:** Change statements like *'Improved system performance'* to *'Improved system performance by **35%** reducing latency by **120ms**.'*\n\n"
 
    markdown += f"#### 2. Skill Alignment for {target_role} 🎯\n"
    markdown += f"I see you have experience with **{skills_str}**. To stand out for {target_role} roles:\n"
    markdown += "- **Action:** Move your technical skills section to the top of your resume, right below your summary.\n"
    markdown += f"- **Action:** If you are targeting {target_role}, ensure that the first bullet point under your most recent role heavily features these core competencies.\n\n"

    markdown += "#### 3. Formatting & ATS Optimization 🤖\n"
    markdown += "- **Formatting:** Ensure you are using a standard, single-column layout. Avoid complex tables or graphics as they can confuse ATS parsers.\n"
    markdown += "- **Keywords:** Mirror the exact phrasing used in the job description you are applying for. If they ask for 'GCP', don't just write 'Google Cloud'.\n\n"
    
    markdown += "#### Final Verdict\n"
    markdown += "You have a solid foundation! Focus on rewriting your experience section to be purely achievement-based rather than responsibility-based."
    
    return markdown

def _call_gemini(api_key, prompt):
    """Call Google Gemini API."""
    if not HAS_GENAI:
        return None, "Gemini libraries not installed"
        
    # Try google.genai SDK
    if genai is not None:
        try:
            client = genai.Client(api_key=api_key)
            for model_name in GEMINI_MODELS:
                try:
                    response = client.models.generate_content(
                        model=model_name,
                        contents=prompt
                    )
                    return response.text, None
                except Exception:
                    continue
        except Exception:
            pass
            
    # Try legacy google.generativeai
    try:
        import google.generativeai as genai_legacy
        genai_legacy.configure(api_key=api_key)
        for model_name in GEMINI_MODELS:
            try:
                model = genai_legacy.GenerativeModel(model_name)
                response = model.generate_content(prompt)
                return response.text, None
            except Exception:
                continue
    except Exception:
        pass
        
    return None, "Gemini API call failed"

def generate_resume_feedback(resume_text, target_role):
    prompt = f"""You are an expert technical recruiter and career coach. 
Review the following resume for a candidate targeting the role of "{target_role}".
Provide concise, actionable feedback on how to improve the resume.
Focus on bullet points, impact (using numbers), and overall structure.
Keep the feedback under 300 words.
Use Markdown format.

Resume Text:
{resume_text[:4000]}"""

    # Attempt to load Gemini API Key (active working provider)
    gemini_key = _load_key(["GEMINI_API_KEY"])
    if gemini_key:
        result, error = _call_gemini(gemini_key, prompt)
        if result:
            return f"### Expert Resume Analysis for {target_role}\n\n" + result

    # Fallback to local rule engine
    return _generate_fallback_feedback(resume_text, target_role)
